//
//  StixTypes.h
//  Stixx
//
//  Created by Bobby Ren on 4/11/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#ifndef Stixx_StixTypes_h
#define Stixx_StixTypes_h


babychick.png
baldeagle.png
bluecrab.png
brownbunny.png
butterfly2.png
butterfly3.png
capuchin.png
cat.png
cheladamonkeyface.png
chipmunk.png
dog_cleo.png
duck.png
fatlizard.png
fly.png
frog.png
frog2.png
giraffehead.png
goldfish.png
judgementalcat.png
kitten.png
kittenface.png
lazydog.png
lemurhead.png
lion.png
lioness.png
mallard.png
meerkat.png
monkeyface.png
monkeyface2.png
ostrichhead.png
owl.png
parrothead.png
peacock.png
penguin.png
redcardinal.png
rhino.png
shybear.png
sittingmonkey.png
snowowl.png
spider.png
spottedbunny.png
squirrel1.png
squirrel2.png
squirrel3.png
swan.png
zebra.png

Comics
ant.png
bomb.png
bone.png
bonk.png
brownanimeeyes.png
cartoonfly.png
chickenhero.png
chimpzilla.png
dynamite.png
evilrobot.png
exclamation.png
greenspaceman.png
hal.png
handgun.png
kaboom.png
kapow.png
lasergun.png
lightning.png
lightsword.png
longsword.png
milesanders_hook.png
milesanders_horns.png
milesanders_lobsterclaw.png
ninja2.png
ninjastar.png
pinkskull.png
plop.png
poof.png
pop.png
pow.png
question.png
rocket.png
shortsword.png
smack.png
speechbubble.png
stickfigure.png
thought_bubble.png
thud.png
thudd.png
zombiehead.png

Cute
abstractbubbles.png
abstractsun.png
babychick.png
babychick2.png
babypenguin.png
bemine.png
blue_splash.png
blueflower.png
bluepenguin.png
bunchofstars.png
cartoonpig.png
cheekymonkey.png
cherryblossomrabbits.png
flowerpower.png
giraffe.png
green_splash.png
happylemon.png
hearts1.png
heartsplenty.png
hippo.png
inksplash.png
ladybug.png
littlebear.png
milesanders_bird.png
milesanders_cat.png
milesanders_crab.png
milesanders_dog.png
milesanders_fish.png
milesanders_flower.png
milesanders_owl.png
milesanders_parrot.png
mole.png
musicnote.png
panda.png
panda2.png
panda3.png
pawprint.png
pink_splash.png
pinkballoon.png
pinkdolphin.png
pinkflower.png
pinkstar.png
purplebutterfly.png
rainbow.png
rainbow2.png
realteddybear.png
red_glowing_heart.png
redrose.png
smallwhale.png
snowflake.png
starexplode.png
swirlyribbons.png
teddy.png
teddyface.png
tulip.png
wackybear.png
yellowflowserborder.png


Face Fun
bandaid.png
beard_scruffy.png
blooddrip.png
crown.png
drop.png
eye_scary.png
eyepatch.png
eyes_bulging.png
eyes_creepycat.png
eyes_crossed.png
eyes_puppy.png
furryears.png
glasses_3d_glasses.png
glasses_aviatorglasses.png
glasses_catglasses.png
hair_afro.png
hair_blondshort.png
hair_blondwithbangs.png
hair_brownbangs.png
hair_brownlong.png
hair_celebrityboy.png
hair_curlylongblond.png
hair_dreadlocks.png
hair_eurostyle.png
hair_platinumblond.png
hair_redshorthair.png
hair_shortblondcosplayhair.png
hair_shortblondguy.psd
hair_shortblue.png
hair_spikyblondcosplay.png
hat_browncap.png
hat_brownstripedcap.png
hat_fedora.png
hat_tophat.png
hockeymask.png
kiss.png
mouth_buckteeth.png
mouth_toothy.png
mouth_toothy2.png
mouth_uglyteeth.png
mouth_vampirefangs.png
nerdytie.png
openmouth.png
partyhat.png
polarbearhat.png
stache_bushy.png
stache_rich.png
surprised_eyes.png


Meme
areyouseriousface.png
censored.png
chubbybaby.png
derp.png
derpeyes.png
fail.png
foreveralone.png
ftw.png
guy_fawkes.png
happycutenessoverload.png
happysmileyface.png
lol.png
lolface.png
megusta.png
noface.png
okayguy.png
omg.png
pleaseface.png
pokerface.png
rawchicken.png
skepticalbaby.png
sleepingbabyface.png
successkid.png
trollface.png
woodface.png
yolo.png
yunoguy.png



Video Games
cubeangry.png
cubecool.png
cubekiss.png
cubeshocked.png
cubesick.png
cubesilly.png
cubesmile.png
cubewink.png
game_coin.png
game_shroom.png
gamecontroller.png
gameinvader.png
gametower.png
handcursor.png
isobuilding.png
mariostar.png
minecraft.png
pacmangreen.png
pirates_chest.png
pressbutton.png
redfireball.png
robohead.png
tallisotower.png
tetris1.png
tetris2.png
tetris3.png
videogame_pipe.png

#endif
